qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=1 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=2 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=3 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=4 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=5 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=6 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=7 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=8 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=9 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=10 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=11 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=12 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=13 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=14 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=15 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=16 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=17 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=18 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=19 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=20 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=21 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=22 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=23 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=24 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=25 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=26 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=27 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=28 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=29 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=30 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=31 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=32 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=33 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=34 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=35 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=36 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=37 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=38 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=39 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=40 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=41 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=42 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=43 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=44 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=45 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=46 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=47 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=48 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=49 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=50 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=51 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=52 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=53 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=54 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=55 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=56 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=57 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=58 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=59 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=60 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=61 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=62 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=63 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=64 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=65 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=66 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=67 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=68 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=69 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=70 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=71 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=72 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=73 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=74 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=75 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=76 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=77 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=78 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=79 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=80 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=81 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=82 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=83 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=84 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=85 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=86 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=87 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=88 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=89 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=90 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=91 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=92 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=93 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=94 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=95 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=96 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=97 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=98 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=99 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=100 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=101 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=102 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=103 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=104 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=105 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=106 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=107 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=108 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=109 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=110 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=111 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=112 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=113 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=114 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=115 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=116 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=117 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=118 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=119 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=120 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=121 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=122 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=123 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=124 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=125 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=126 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=127 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=128 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=129 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=130 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=131 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=132 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=133 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=134 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=135 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=136 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=137 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=138 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=139 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=140 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=141 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=142 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=143 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=144 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=145 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=146 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=147 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=148 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=149 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=150 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=151 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=152 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=153 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=154 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=155 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=156 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=157 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=158 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=159 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=160 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=161 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=162 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=163 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=164 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=165 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=166 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=167 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=168 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=169 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=170 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=171 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=172 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=173 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=174 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=175 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=176 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=177 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=178 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=179 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=180 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=181 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=182 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=183 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=184 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=185 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=186 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=187 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=188 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=189 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=190 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=191 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=192 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=193 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=194 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=195 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=196 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=197 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=198 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=199 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=200 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=201 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=202 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=203 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=204 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=205 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=206 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=207 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=208 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=209 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=210 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=211 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=212 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=213 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=214 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=215 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=216 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=217 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=218 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=219 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=220 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=221 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=222 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=223 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=224 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=225 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=226 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=227 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=228 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=229 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=230 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=231 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=232 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=233 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=234 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=235 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=236 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=237 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=238 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=239 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=240 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=241 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=242 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=243 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=244 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=245 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=246 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=247 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=248 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=249 qtl2blup_one.sh
qsub -o log_blup_output.txt -e log_blup_error.txt -v nparts=250,part=250 qtl2blup_one.sh
