qsub -o log_output.txt -e log_error.txt -v nparts=500,part=1 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=2 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=3 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=4 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=5 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=6 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=7 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=8 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=9 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=10 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=11 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=12 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=13 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=14 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=15 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=16 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=17 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=18 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=19 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=20 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=21 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=22 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=23 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=24 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=25 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=26 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=27 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=28 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=29 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=30 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=31 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=32 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=33 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=34 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=35 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=36 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=37 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=38 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=39 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=40 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=41 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=42 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=43 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=44 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=45 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=46 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=47 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=48 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=49 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=50 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=51 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=52 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=53 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=54 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=55 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=56 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=57 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=58 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=59 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=60 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=61 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=62 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=63 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=64 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=65 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=66 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=67 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=68 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=69 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=70 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=71 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=72 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=73 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=74 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=75 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=76 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=77 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=78 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=79 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=80 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=81 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=82 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=83 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=84 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=85 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=86 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=87 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=88 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=89 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=90 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=91 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=92 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=93 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=94 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=95 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=96 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=97 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=98 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=99 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=100 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=101 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=102 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=103 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=104 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=105 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=106 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=107 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=108 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=109 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=110 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=111 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=112 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=113 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=114 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=115 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=116 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=117 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=118 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=119 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=120 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=121 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=122 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=123 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=124 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=125 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=126 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=127 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=128 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=129 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=130 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=131 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=132 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=133 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=134 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=135 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=136 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=137 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=138 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=139 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=140 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=141 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=142 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=143 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=144 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=145 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=146 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=147 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=148 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=149 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=150 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=151 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=152 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=153 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=154 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=155 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=156 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=157 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=158 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=159 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=160 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=161 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=162 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=163 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=164 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=165 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=166 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=167 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=168 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=169 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=170 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=171 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=172 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=173 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=174 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=175 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=176 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=177 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=178 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=179 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=180 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=181 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=182 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=183 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=184 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=185 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=186 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=187 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=188 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=189 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=190 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=191 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=192 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=193 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=194 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=195 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=196 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=197 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=198 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=199 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=200 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=201 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=202 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=203 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=204 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=205 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=206 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=207 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=208 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=209 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=210 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=211 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=212 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=213 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=214 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=215 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=216 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=217 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=218 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=219 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=220 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=221 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=222 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=223 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=224 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=225 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=226 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=227 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=228 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=229 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=230 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=231 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=232 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=233 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=234 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=235 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=236 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=237 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=238 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=239 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=240 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=241 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=242 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=243 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=244 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=245 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=246 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=247 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=248 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=249 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=250 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=251 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=252 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=253 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=254 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=255 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=256 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=257 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=258 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=259 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=260 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=261 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=262 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=263 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=264 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=265 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=266 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=267 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=268 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=269 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=270 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=271 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=272 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=273 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=274 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=275 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=276 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=277 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=278 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=279 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=280 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=281 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=282 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=283 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=284 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=285 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=286 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=287 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=288 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=289 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=290 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=291 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=292 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=293 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=294 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=295 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=296 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=297 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=298 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=299 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=300 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=301 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=302 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=303 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=304 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=305 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=306 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=307 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=308 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=309 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=310 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=311 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=312 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=313 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=314 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=315 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=316 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=317 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=318 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=319 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=320 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=321 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=322 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=323 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=324 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=325 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=326 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=327 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=328 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=329 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=330 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=331 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=332 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=333 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=334 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=335 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=336 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=337 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=338 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=339 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=340 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=341 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=342 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=343 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=344 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=345 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=346 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=347 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=348 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=349 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=350 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=351 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=352 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=353 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=354 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=355 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=356 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=357 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=358 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=359 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=360 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=361 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=362 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=363 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=364 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=365 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=366 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=367 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=368 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=369 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=370 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=371 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=372 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=373 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=374 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=375 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=376 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=377 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=378 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=379 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=380 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=381 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=382 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=383 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=384 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=385 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=386 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=387 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=388 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=389 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=390 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=391 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=392 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=393 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=394 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=395 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=396 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=397 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=398 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=399 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=400 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=401 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=402 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=403 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=404 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=405 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=406 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=407 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=408 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=409 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=410 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=411 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=412 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=413 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=414 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=415 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=416 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=417 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=418 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=419 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=420 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=421 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=422 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=423 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=424 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=425 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=426 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=427 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=428 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=429 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=430 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=431 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=432 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=433 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=434 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=435 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=436 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=437 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=438 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=439 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=440 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=441 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=442 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=443 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=444 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=445 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=446 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=447 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=448 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=449 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=450 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=451 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=452 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=453 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=454 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=455 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=456 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=457 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=458 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=459 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=460 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=461 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=462 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=463 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=464 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=465 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=466 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=467 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=468 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=469 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=470 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=471 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=472 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=473 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=474 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=475 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=476 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=477 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=478 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=479 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=480 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=481 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=482 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=483 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=484 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=485 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=486 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=487 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=488 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=489 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=490 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=491 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=492 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=493 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=494 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=495 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=496 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=497 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=498 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=499 qtl2int_one.sh
qsub -o log_output.txt -e log_error.txt -v nparts=500,part=500 qtl2int_one.sh
